// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fesbcknsvqqiqjqipiql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlc2Jja25zdnFxaXFqcWlwaXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDQxNjYsImV4cCI6MjA2NTU4MDE2Nn0._CTDT3y4Tr2flaMJ-MGv2h3iHz3ZXu7bj8ChL-XFHwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);